### ISSUE TITLE
Release checklist 2020-11-02

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#109]
- [x]  modify client and server protocol version numbers (this is a breaking release)

- [x] arrange server downtime/align with some time before the scheduled update time

- [x] push new release to git site

- [x] add version.txt to release branch e.g. with another commit, and keep this here for backward compatibility
